#!/usr/bin/env bash
# =============================================================================
# Axiarch §6 ANTI-FULL-OVERWRITE Enforcement (PreToolUse hook)
# https://github.com/s-kyono/axiarch
#
# Physically blocks Write tool calls that target existing files, directing the
# AI to use Edit (diff-based) instead. This reduces the known §6
# ANTI-FULL-OVERWRITE violation pattern that reminder-only enforcement cannot
# reliably stop.
#
# Hook contract (PreToolUse):
#   - stdin: JSON with `tool_name`, `tool_input.file_path`, etc.
#   - stdout: optional JSON output controlling the tool decision
#   - exit code 2 + stderr message: also blocks the tool
#
# Decision logic:
#   1. Tool is not "Write" → allow (exit 0, no output)
#   2. file_path is empty/missing → allow
#   3. file_path does not exist on disk → creation, allow
#   4. file_path exists → DENY with §6 violation message
#
# Whitelist support (future-friendly):
#   `.claude/axiarch-overwrite-allow.txt` or `.codex/axiarch-overwrite-allow.txt` (one path/glob per line) bypasses the
#   block — useful for autogenerated artefacts. Comments (#) and empty lines
#   are skipped.
#
# No external dependencies (jq optional). Pure POSIX shell.
# =============================================================================

set -uo pipefail

# -----------------------------------------------------------------------------
# Resolve project directory
# -----------------------------------------------------------------------------
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-}"
if [[ -z "${PROJECT_DIR}" || ! -d "${PROJECT_DIR}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
fi

# -----------------------------------------------------------------------------
# Read hook input from stdin
# -----------------------------------------------------------------------------
INPUT="$(cat)"

# -----------------------------------------------------------------------------
# Extract tool_name and file_path
# Prefer jq; fall back to grep + sed for jq-less environments.
# -----------------------------------------------------------------------------
TOOL_NAME=""
FILE_PATH=""

if command -v jq &>/dev/null; then
  TOOL_NAME=$(printf '%s' "${INPUT}" | jq -r '.tool_name // empty' 2>/dev/null || true)
  FILE_PATH=$(printf '%s' "${INPUT}" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
else
  TOOL_NAME=$(printf '%s' "${INPUT}" \
    | grep -oE '"tool_name"[[:space:]]*:[[:space:]]*"[^"]+"' \
    | head -1 | sed -E 's/.*"([^"]+)"[[:space:]]*$/\1/')
  FILE_PATH=$(printf '%s' "${INPUT}" \
    | grep -oE '"file_path"[[:space:]]*:[[:space:]]*"[^"]+"' \
    | head -1 | sed -E 's/.*"([^"]+)"[[:space:]]*$/\1/')
fi

# -----------------------------------------------------------------------------
# Allow: tool is not Write
# -----------------------------------------------------------------------------
if [[ "${TOOL_NAME}" != "Write" ]]; then
  exit 0
fi

# -----------------------------------------------------------------------------
# Allow: file_path is empty/missing (let downstream layers decide)
# -----------------------------------------------------------------------------
if [[ -z "${FILE_PATH}" ]]; then
  exit 0
fi

# -----------------------------------------------------------------------------
# Allow: file does not exist (Write = creation, not overwrite)
# -----------------------------------------------------------------------------
if [[ ! -f "${FILE_PATH}" ]]; then
  exit 0
fi

# -----------------------------------------------------------------------------
# Whitelist: bypass when matched in .claude/axiarch-overwrite-allow.txt or .codex/...
# -----------------------------------------------------------------------------
ALLOW_FILE=""
if [[ -f "${PROJECT_DIR}/.claude/axiarch-overwrite-allow.txt" ]]; then
  ALLOW_FILE="${PROJECT_DIR}/.claude/axiarch-overwrite-allow.txt"
elif [[ -f "${PROJECT_DIR}/.codex/axiarch-overwrite-allow.txt" ]]; then
  ALLOW_FILE="${PROJECT_DIR}/.codex/axiarch-overwrite-allow.txt"
fi

if [[ -n "${ALLOW_FILE}" ]]; then
  while IFS= read -r pattern || [[ -n "${pattern}" ]]; do
    # Skip empty lines and comments
    [[ -z "${pattern}" || "${pattern}" =~ ^[[:space:]]*# ]] && continue
    # Trim leading/trailing whitespace
    pattern="$(printf '%s' "${pattern}" | sed -E 's/^[[:space:]]+|[[:space:]]+$//g')"
    [[ -z "${pattern}" ]] && continue
    # Glob match (case-sensitive)
    # shellcheck disable=SC2053
    if [[ "${FILE_PATH}" == ${pattern} ]]; then
      exit 0
    fi
  done < "${ALLOW_FILE}"
fi

# -----------------------------------------------------------------------------
# Deny: existing file + Write tool = potential §6 ANTI-FULL-OVERWRITE violation
# -----------------------------------------------------------------------------
REASON_JA="AGENTS.md §6 ANTI-FULL-OVERWRITE: 既存ファイル '${FILE_PATH}' を Write tool で全面書き換えしようとしています。差分編集には Edit tool を使用してください。意図的に全面書き換えが必要な場合はユーザー明示承認のうえで .claude/axiarch-overwrite-allow.txt または .codex/axiarch-overwrite-allow.txt にパスを追加してください。"
REASON_EN="AGENTS.md §6 ANTI-FULL-OVERWRITE: file '${FILE_PATH}' already exists; the AI must use Edit (diff-based) instead of Write (full overwrite). If full overwrite is genuinely needed, ask the user for explicit approval and add the path to .claude/axiarch-overwrite-allow.txt or .codex/axiarch-overwrite-allow.txt."

# Emit JSON output for hook contract (decision: block + reason)
escape_json_value() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\b'/\\b}"
  s="${s//$'\f'/\\f}"
  s="${s//$'\n'/\\n}"
  s="${s//$'\r'/\\r}"
  s="${s//$'\t'/\\t}"
  printf '%s' "$s"
}
REASON_FULL="${REASON_JA} / ${REASON_EN}"
ESCAPED=$(escape_json_value "${REASON_FULL}")
printf '%s' '{"decision":"block","reason":"'"${ESCAPED}"'"}'

# Also write a human-readable message to stderr for transcripts that may not
# render the JSON decision payload.
printf '\n[axiarch:protect-antifull] BLOCKED — %s\n' "${REASON_FULL}" >&2

# Exit code 2 — Claude Code treats this as a hard block on the tool call.
exit 2
